file_format: "1"
id: elara
name: Elara
type: shield
url: https://google.com
requires: [pro_micro]
features:
  - keys
exposes:
  - pointer
  - display
siblings:
  - elara_left 
  - elara_right